# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ruler_calc',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/ruler_calc',
                'lib_path': 'ruler_calc'},
  'syms': { 'ruler_calc.api': { 'ruler_calc.api.ApiClient': ('api.html#apiclient', 'ruler_calc/api.py'),
                                'ruler_calc.api.ApiClient.__init__': ('api.html#apiclient.__init__', 'ruler_calc/api.py'),
                                'ruler_calc.api.ApiClient.hlsd': ('api.html#apiclient.hlsd', 'ruler_calc/api.py'),
                                'ruler_calc.api.ApiClient.main': ('api.html#apiclient.main', 'ruler_calc/api.py'),
                                'ruler_calc.api.ApiClient.main2': ('api.html#apiclient.main2', 'ruler_calc/api.py'),
                                'ruler_calc.api.ApiClient.otsu': ('api.html#apiclient.otsu', 'ruler_calc/api.py'),
                                'ruler_calc.api.ApiClient.skelton': ('api.html#apiclient.skelton', 'ruler_calc/api.py')},
            'ruler_calc.core': {'ruler_calc.core.foo': ('nbs/core.html#foo', 'ruler_calc/core.py')}}}